#!/usr/bin/env python3
"""Interactive client to talk to local agents via A2A (gRPC)."""

import asyncio
import json
import sys
from typing import Optional

import grpc
import grpc.aio
import structlog

from pixell_runtime.proto import agent_pb2, agent_pb2_grpc

logger = structlog.get_logger()


class AgentClient:
    """Client for communicating with local agents via A2A (gRPC)."""

    def __init__(self, host: str = "localhost", port: int = 50051):
        """Initialize the agent client.

        Args:
            host: Hostname of the local PAR instance
            port: Port for gRPC (50051 for local A2A)
        """
        self.host = host
        self.port = port

        # Create insecure channel for local testing
        self.channel = grpc.aio.insecure_channel(f"{host}:{port}")
        self.stub = agent_pb2_grpc.AgentServiceStub(self.channel)

    async def check_health(self) -> dict:
        """Check if the agent is healthy.

        Returns:
            Health status dictionary
        """
        try:
            response = await self.stub.Health(agent_pb2.Empty())
            return {
                "ok": response.ok,
                "message": response.message,
                "timestamp": response.timestamp
            }
        except grpc.RpcError as e:
            logger.error("Health check failed", error=str(e), code=e.code())
            raise

    async def describe_capabilities(self) -> dict:
        """Get agent capabilities.

        Returns:
            Capabilities dictionary with methods and metadata
        """
        try:
            response = await self.stub.DescribeCapabilities(agent_pb2.Empty())
            return {
                "methods": list(response.methods),
                "metadata": dict(response.metadata)
            }
        except grpc.RpcError as e:
            logger.error("Failed to describe capabilities", error=str(e), code=e.code())
            raise

    async def invoke(
        self,
        action: str,
        parameters: dict
    ) -> dict:
        """Invoke an action on the agent.

        Args:
            action: The action name (e.g., "process_data", "calculate")
            parameters: Parameters for the action

        Returns:
            Response from the agent
        """
        # Convert parameters to string dict (protobuf limitation)
        str_params = {k: json.dumps(v) if not isinstance(v, str) else v
                      for k, v in parameters.items()}

        request = agent_pb2.ActionRequest(
            action=action,
            parameters=str_params,
            request_id=""  # Will be generated by agent if empty
        )

        logger.info("Invoking agent via A2A",
                   action=action,
                   parameters=list(parameters.keys()))

        try:
            response = await self.stub.Invoke(request)

            result = {
                "success": response.success,
                "result": response.result,
                "error": response.error if response.error else None,
                "request_id": response.request_id,
                "duration_ms": response.duration_ms
            }

            logger.info("Agent responded",
                       success=result["success"],
                       duration_ms=result.get("duration_ms"))

            return result
        except grpc.RpcError as e:
            logger.error("Invocation failed", error=str(e), code=e.code())
            raise

    async def ping(self) -> dict:
        """Ping the agent to check connectivity.

        Returns:
            Pong response with message and timestamp
        """
        try:
            response = await self.stub.Ping(agent_pb2.Empty())
            return {
                "message": response.message,
                "timestamp": response.timestamp
            }
        except grpc.RpcError as e:
            logger.error("Ping failed", error=str(e), code=e.code())
            raise

    async def close(self):
        """Close the gRPC channel."""
        await self.channel.close()


async def interactive_mode(client: AgentClient):
    """Run interactive mode to chat with the local agent.

    Args:
        client: The agent client
    """
    print(f"\n🤖 Connected to local agent")
    print("=" * 60)

    # Check health
    try:
        health = await client.check_health()
        print(f"Health: {'✅ OK' if health.get('ok') else '❌ Not OK'}")
        print(f"Message: {health.get('message', 'N/A')}")
        print(f"Timestamp: {health.get('timestamp')}")
    except Exception as e:
        print(f"⚠️  Health check failed: {e}")
        print("Continuing anyway...")

    # Get capabilities
    try:
        print("\n📋 Getting agent capabilities...")
        capabilities = await client.describe_capabilities()
        print(f"Available methods: {', '.join(capabilities.get('methods', []))}")
        if capabilities.get('metadata'):
            print(f"Metadata: {capabilities['metadata']}")
    except Exception as e:
        print(f"⚠️  Failed to get capabilities: {e}")

    print("\n" + "=" * 60)
    print("Chat with the local AI agent (or 'quit' to exit)")
    print("")
    print("You can:")
    print("  - Process data: process_data")
    print("  - Calculate: calculate")
    print("  - Get status: get_status")
    print("  - Just chat naturally!")
    print("=" * 60 + "\n")

    while True:
        try:
            # Get input
            user_input = input("\n💬 You: ").strip()

            if not user_input:
                continue

            if user_input.lower() in ['quit', 'exit', 'q']:
                print("\n👋 Goodbye!")
                break

            # Determine action and parameters based on input format
            if user_input.startswith("calculate:"):
                # Calculate mode: calculate:a:5,b:3,operation:add
                parts = user_input.split(':', 1)
                if len(parts) > 1:
                    params_str = parts[1]
                    parameters = {}
                    for param in params_str.split(','):
                        if ':' in param:
                            key, value = param.split(':', 1)
                            try:
                                # Try to convert to number
                                parameters[key.strip()] = float(value.strip())
                            except ValueError:
                                parameters[key.strip()] = value.strip()
                    
                    action = "calculate"
                else:
                    print("⚠️  Format: calculate:a:5,b:3,operation:add")
                    continue
            elif user_input.startswith("process:"):
                # Process data mode: process:Hello World
                data = user_input.split(':', 1)[1] if ':' in user_input else user_input
                action = "process_data"
                parameters = {"data": data}
            elif user_input.startswith("status"):
                # Status mode
                action = "get_status"
                parameters = {}
            else:
                # Plain conversation mode
                action = "chat"
                parameters = {
                    "message": user_input
                }

            # Invoke agent
            print(f"\n🔄 Sending to agent via A2A...")
            result = await client.invoke(
                action=action,
                parameters=parameters
            )

            # Display result
            print("\n" + "=" * 60)
            if result.get('success'):
                print("✅ Success!")
                print(f"\n{result.get('result', 'No response')}")
                if result.get('duration_ms'):
                    print(f"\n⏱️  Duration: {result['duration_ms']}ms")
            else:
                print("❌ Failed!")
                if result.get('error'):
                    print(f"Error: {result['error']}")
            print("=" * 60)

        except KeyboardInterrupt:
            print("\n\n👋 Goodbye!")
            break
        except grpc.RpcError as e:
            print(f"\n❌ gRPC Error: {e.details()}")
            print(f"Code: {e.code()}")
        except Exception as e:
            print(f"\n❌ Error: {e}")
            logger.exception("Invocation failed")


async def single_invocation(
    client: AgentClient,
    action: str,
    parameters: dict
):
    """Make a single invocation to the agent.

    Args:
        client: The agent client
        action: Action to invoke
        parameters: Parameters for the action
    """
    print(f"\n🤖 Invoking local agent via A2A")
    print(f"Action: {action}")
    print(f"Parameters: {parameters}\n")

    result = await client.invoke(
        action=action,
        parameters=parameters
    )

    print("=" * 60)
    if result.get('success'):
        print("✅ Success!")
        print(f"\n{result.get('result', 'No response')}")
        if result.get('duration_ms'):
            print(f"\n⏱️  Duration: {result['duration_ms']}ms")
    else:
        print("❌ Failed!")
        if result.get('error'):
            print(f"Error: {result['error']}")
    print("=" * 60)


async def main():
    """Main entry point."""
    print("🤖 Local Agent Client (A2A/gRPC)")
    print("=" * 60)

    # Use localhost for local testing
    host = "localhost"
    port = 50051

    print(f"\n🔗 Connecting to {host}:{port}")
    print("📍 Local agent A2A endpoint")

    client = AgentClient(host=host, port=port)

    try:
        # Always run interactive mode
        await interactive_mode(client)
    finally:
        await client.close()


if __name__ == "__main__":
    asyncio.run(main())
